---
title: "Intro R"
author: "Sungbae Chun"
date: "5/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Vectors

```{r vector, echo=T}
v = c(130,20,30)
print("This is a vector")
print(v)
```

### Named vectors

```{r nvec, echo=T}
v = c(175,190)
c("Sungbae","Max") -> names(v)
print(v)

#you can access
print(v["Sungbae"])
#or
print(v[1])

#multiple selection
print(v[1:2])

#logical selection
print(v>180)
print(v[v>180])
```

## Matrices

```{r mat, echo=T}
print(matrix(1:9, byrow=T, nrow=3))
print(matrix(1:9, byrow=F, nrow=3))

#combining several vectors
v1 = c(1,2,3)
v2 = c(4,5,6)
print(c(v1,v2))
matrix(c(v1,v2),byrow=T,ncol=3) -> newmat
newmat

#naming a matrix
colnames(newmat) <- c("one","two","three")
rownames(newmat) <- c("rone","rtwo")
print(newmat)
print(rowSums(newmat))

#adding a column
newmat <- cbind(newmat,rowSums(newmat))
print(newmat)
newmat <- rbind(newmat, colSums(newmat))
print(newmat)

print(newmat[,2])
print(newmat[1,])

# * is python-like elementwise
print(c(1,2,3)*c(0,2,3))
print(diag(x=1,nrow=3,ncol=3)*matrix(1:9,byrow=T,nrow =3))
```


## Factors

Are variables used to store **categorical** variables

```{r factor, echo = T}
gen_vec <- c("M","F","F","F","M")
fac_gen <- factor(gen_vec)
print(fac_gen)



#Be careful with the order
fac_gen
v = c("Female","Male")
w = c("Male","Female")
levels(fac_gen) = v
print(fac_gen)

#but
levels(fac_gen) = w
print(fac_gen)

print(summary(fac_gen))
print(summary(w))

#comparing fac_gen[1] > fac_gen[2] will give NA
#by default, factors are not comparable

#ordered factors
speed_vector <- c("medium","slow","slow","medium","fast")

#creating ordered factors
fac_sp = factor(speed_vector,ordered = T,
                levels = c("slow","medium",
                           "fast"))
fac_sp
print(paste(fac_sp[1],"is greater than",
            fac_sp[2],":",fac_sp[1]>fac_sp[2]))
```

## Dataframes


`str(df)` and `head(df)` are two simplest ways to view a dataframe<br>

<br>
**Creating** a dataframe
```{r dat, echo=T}
name = c("Sungbae","Max")
heights = c(175,190)
is_cs = c(F,T)
is_math = c(T,F)

df = data.frame(name,heights,is_cs,is_math)
print(df)
print(summary(df))
print(str(df))
print(df[1,])
print(df[,1])
print(df[,"name"])
print(df["name"])
print(df$name)
print(df[is_math,])
print(df[is_cs,])
subset(df, subset = heights>180)

a = c(100,10,1000)
print(order(a))
print(a[order(a)])

#sorting df
positions = order(df$heights,decreasing = T) 
df[positions,]
```


## Lists

Can store **anything**

```{r lst, echo=T}
my_list = list(10,30,"wow",c(10,20))
my_list

my_list = list("dataframe" = df,
               vector = c(10,20))
my_list

names(my_list) <- c("df","v")
print(my_list)

my_list[["v"]]
#or
my_list$v
```
